typography_spectrum: 0.1950672073289752
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.3308275092858821
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.77678
analytics:
  google: null
  facebook: null
  twitter: null
name: Pyramid Images
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: An Apple A Day
description: Advice from a Maven
purpose: []
